# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F8CsWGVbxgvdt55RsucghkBZQiaNVdxg
"""

atakimi = ['arda', 'boran', 'yağmur', 'ardayılmaz']

sayaç = 1
for isim in atakimi:
    harf_sayısı = 0
    for harf in isim:
        harf_sayısı += 1
    print(f"{sayaç}. {isim}: {harf_sayısı} harf")
    sayaç += 1

atakimi = ['arda', 'boran', 'yağmur', 'ardayılmaz']
aout = []

for i in atakimi:
    sayac = 0
    for harf in range(len(i)):
        sayac += 1
    aout.append(sayac)
    print(sayac)

g = "Dünya Dopingle Mücadele Ajansı (WADA) çok sayıda Türk sporcuda doping tespit edildiğini açıkladı. Yapılan açıklamaya göre; halterde 7, boksta 3 ve güreşte 2 sporcu doping cezası aldı."
kelimeler = g.split(' ')

def donustur(a):
    sayac = []
    for kelime in a:
        uzunluk = len(kelime)
        sayac.append(uzunluk)
        print(uzunluk)
    return sayac

b = donustur(kelimeler)
print(b)